import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync, readFileSync, existsSync, readdirSync } from 'fs';
import os from 'os';
import path from 'path';
import { fileURLToPath } from 'url';

import { generateApiTypes } from '../codegen-api.js';
import { verifyCodegen } from '../verify-codegen.js';

/**
 * T051 — codegen + drift verification tests.
 *
 * Three contract assertions for AS-6:
 *   1. Determinism: the same snapshot produces byte-identical output
 *      across two runs. Without this, the drift gate is theatre.
 *   2. Drift detection: verify-codegen exits non-zero (returns a
 *      "drifted" result) when the committed file has been edited.
 *   3. Match: verify-codegen exits zero (returns "match") when the
 *      committed file equals what the runner would produce.
 *
 * The tests use the real openapi-typescript binding against the real
 * scripts/openapi-snapshot.json. No network, no Electron — pure tooling.
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const SNAPSHOT_PATH = path.join(REPO_ROOT, 'scripts', 'openapi-snapshot.json');

let tmpDir: string;

beforeEach(() => {
  tmpDir = mkdtempSync(path.join(os.tmpdir(), 'pos-pulse-codegen-'));
});

afterEach(() => {
  rmSync(tmpDir, { recursive: true, force: true });
});

describe('generateApiTypes — determinism', () => {
  // Timeout raised to 15 s: two back-to-back openapiTS calls plus V8
  // coverage instrumentation and subprocess cold-start can exceed 5 s on
  // slow CI runners. The assertion itself is unchanged.
  it('produces byte-identical output across two runs from the same snapshot', async () => {
    const a = path.join(tmpDir, 'a.ts');
    const b = path.join(tmpDir, 'b.ts');

    await generateApiTypes({ source: 'local', snapshotPath: SNAPSHOT_PATH, outPath: a });
    await generateApiTypes({ source: 'local', snapshotPath: SNAPSHOT_PATH, outPath: b });

    const aBytes = readFileSync(a);
    const bBytes = readFileSync(b);
    expect(aBytes.equals(bBytes)).toBe(true);
  }, 15_000);

  it('writes the generated-file header sentinel', async () => {
    const out = path.join(tmpDir, 'out.ts');
    await generateApiTypes({ source: 'local', snapshotPath: SNAPSHOT_PATH, outPath: out });
    const text = readFileSync(out, 'utf8');
    expect(text).toMatch(/AUTOGENERATED/);
    expect(text).toMatch(/DO NOT EDIT/);
    expect(text).toMatch(/npm run codegen:api/);
  });

  it('uses LF line endings only (no CR)', async () => {
    const out = path.join(tmpDir, 'out.ts');
    await generateApiTypes({ source: 'local', snapshotPath: SNAPSHOT_PATH, outPath: out });
    const buf = readFileSync(out);
    // Reject any 0x0D byte; LF (0x0A) is fine.
    expect(buf.includes(0x0d)).toBe(false);
  });
});

describe('verifyCodegen', () => {
  // Timeout raised to 15 s on three tests that call generateApiTypes()
  // before the verify step. Same rationale as the sibling determinism
  // test at line 53 (PR #37): two back-to-back openapiTS calls plus
  // V8 coverage instrumentation and subprocess cold-start can exceed
  // the default 5 s on slow CI runners — and the post-2026-05-28
  // snapshot expansion (PR #272's 6 new TerminalPairResponse fields
  // + future contract pins) pushes the codegen pass slightly longer,
  // tipping these tests over the 5 s edge reliably. The assertions
  // themselves are unchanged.
  //
  // The "missing" test (line 117) does NOT call generateApiTypes()
  // first, so it stays at the default 5 s timeout.
  it('returns "match" when the committed file equals fresh codegen', async () => {
    const committed = path.join(tmpDir, 'committed.ts');
    await generateApiTypes({ source: 'local', snapshotPath: SNAPSHOT_PATH, outPath: committed });

    const result = await verifyCodegen({
      snapshotPath: SNAPSHOT_PATH,
      committedPath: committed,
    });

    expect(result.status).toBe('match');
    expect(result.exitCode).toBe(0);
  }, 15_000);

  it('returns "drifted" with a non-zero exit code when the committed file was edited', async () => {
    const committed = path.join(tmpDir, 'committed.ts');
    await generateApiTypes({ source: 'local', snapshotPath: SNAPSHOT_PATH, outPath: committed });

    // Append junk to simulate a hand-edit.
    const original = readFileSync(committed, 'utf8');
    writeFileSync(committed, original + '\n// junk appended by test\n', 'utf8');

    const result = await verifyCodegen({
      snapshotPath: SNAPSHOT_PATH,
      committedPath: committed,
    });

    expect(result.status).toBe('drifted');
    expect(result.exitCode).not.toBe(0);
    expect(result.message).toMatch(/codegen:api/);
  }, 15_000);

  it('returns "missing" with a non-zero exit code when the committed file does not exist', async () => {
    const result = await verifyCodegen({
      snapshotPath: SNAPSHOT_PATH,
      committedPath: path.join(tmpDir, 'does-not-exist.ts'),
    });

    expect(result.status).toBe('missing');
    expect(result.exitCode).not.toBe(0);
    expect(result.message).toMatch(/codegen:api/);
  });

  it('cleans up its temp file on the match path', async () => {
    const committed = path.join(tmpDir, 'committed.ts');
    await generateApiTypes({ source: 'local', snapshotPath: SNAPSHOT_PATH, outPath: committed });

    const before = listTempCodegenFiles();
    await verifyCodegen({ snapshotPath: SNAPSHOT_PATH, committedPath: committed });
    const after = listTempCodegenFiles();

    // The verify routine creates and deletes its own temp file; the count
    // of leftover pos-pulse-verify-* files in os.tmpdir() must not grow.
    expect(after.length).toBeLessThanOrEqual(before.length);
  }, 15_000);
});

function listTempCodegenFiles(): string[] {
  // Best-effort: list any verify temp files. Returning [] on read errors
  // keeps the test resilient to platform tmpdir quirks; the real
  // assertion is that the count does not GROW across the verify call.
  try {
    return readdirSync(os.tmpdir()).filter((f) => f.startsWith('pos-pulse-verify-'));
  } catch {
    return [];
  }
}

// Sanity: every test path requires the snapshot to exist. If it doesn't
// the suite is meaningless — fail loud.
describe('snapshot precondition', () => {
  it('scripts/openapi-snapshot.json exists', () => {
    expect(existsSync(SNAPSHOT_PATH)).toBe(true);
  });
});
