/**
 * T052 — OpenAPI → TypeScript types codegen runner.
 *
 * Reads either a pinned local snapshot (default) or fetches the live
 * platform OpenAPI doc (opt-in via `--source=live`), runs
 * `openapi-typescript` v7 programmatically, and writes a deterministic
 * TypeScript module to `src/shared/api-types.ts`.
 *
 * Determinism contract (T051):
 *   - Same input snapshot → byte-identical output across runs.
 *   - Output uses LF line endings only (no CR), even on Windows.
 *   - Every option is pinned explicitly so a future contributor cannot
 *     regenerate with different defaults and silently trip
 *     `verify-codegen`.
 *   - Header sentinel ("AUTOGENERATED — DO NOT EDIT") is part of the
 *     committed bytes; reading the first line tells humans not to edit.
 *
 * CLI:
 *   tsx scripts/codegen-api.ts                # uses scripts/openapi-snapshot.json
 *   tsx scripts/codegen-api.ts --source=live  # fetches https://api.smartdatapulse.tech/openapi.json
 */

import { readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import openapiTS, { astToString, type OpenAPITSOptions } from 'openapi-typescript';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');

const DEFAULT_SNAPSHOT_PATH = path.join(REPO_ROOT, 'scripts', 'openapi-snapshot.json');
const DEFAULT_OUT_PATH = path.join(REPO_ROOT, 'src', 'shared', 'api-types.ts');
const LIVE_URL = 'https://api.smartdatapulse.tech/openapi.json';

const HEADER = [
  '// AUTOGENERATED — DO NOT EDIT.',
  '// This file is the output of `npm run codegen:api`, which derives types',
  '// from scripts/openapi-snapshot.json (pinned). To refresh from the live',
  '// platform OpenAPI doc, run `tsx scripts/codegen-api.ts --source=live`',
  '// and commit both the new snapshot and the regenerated types.',
  '',
  '',
].join('\n');

/**
 * Pinned `openapi-typescript` options. Every option that affects output
 * shape is set explicitly. Default-tracking via "// uses lib default" is
 * deliberately avoided — the lib's defaults can change minor-version, and
 * silent default drift would defeat the verify gate.
 */
const FIXED_OPTIONS: OpenAPITSOptions = {
  additionalProperties: false,
  alphabetize: true, // sort keys alphabetically — pure determinism guard
  arrayLength: false,
  emptyObjectsUnknown: false,
  defaultNonNullable: true,
  excludeDeprecated: false,
  immutable: false,
  silent: true,
  exportType: false,
  enum: false,
  enumValues: false,
  conditionalEnums: false,
  dedupeEnums: false,
  pathParamsAsTypes: false,
  propertiesRequiredByDefault: false,
  rootTypes: false,
  rootTypesNoSchemaPrefix: false,
  rootTypesKeepCasing: false,
  makePathsEnum: false,
  generatePathParams: false,
  readWriteMarkers: false,
};

export type CodegenSource = 'local' | 'live';

export interface GenerateApiTypesOptions {
  /** Where to source the OpenAPI doc from. Default = 'local'. */
  source: CodegenSource;
  /** Path to the local pinned snapshot (used when source='local'). */
  snapshotPath: string;
  /** Where to write the generated .ts file. */
  outPath: string;
  /** Override live URL for testing. Defaults to the platform URL. */
  liveUrl?: string;
}

/**
 * Generate TypeScript types from an OpenAPI source and write the
 * deterministic, header-prefixed result to `outPath`. Returns the
 * generated string (sans final newline) for callers that want to byte-compare.
 */
export async function generateApiTypes(options: GenerateApiTypesOptions): Promise<string> {
  const source =
    options.source === 'live'
      ? new URL(options.liveUrl ?? LIVE_URL)
      : (JSON.parse(readFileSync(options.snapshotPath, 'utf8')) as Parameters<typeof openapiTS>[0]);

  const ast = await openapiTS(source, FIXED_OPTIONS);
  const body = astToString(ast);
  // Force LF: replace any CRLF the lib (or the tsx runtime) may emit on Windows.
  const normalized = body.replace(/\r\n/g, '\n');
  // Single trailing newline, deterministic.
  const ensureTrailingLf = normalized.endsWith('\n') ? normalized : normalized + '\n';
  const finalText = HEADER + ensureTrailingLf;

  writeFileSync(options.outPath, finalText, { encoding: 'utf8' });
  return finalText;
}

async function main(argv: string[]): Promise<void> {
  const sourceFlag = argv.find((a) => a.startsWith('--source='));
  const source: CodegenSource =
    sourceFlag === '--source=live'
      ? 'live'
      : sourceFlag === '--source=local' || sourceFlag === undefined
        ? 'local'
        : (() => {
            console.error(
              `[codegen-api] invalid --source flag: ${sourceFlag}. Expected --source=local or --source=live.`,
            );
            process.exit(2);
          })();

  console.log(
    `[codegen-api] generating ${path.relative(REPO_ROOT, DEFAULT_OUT_PATH)} from source=${source}`,
  );
  await generateApiTypes({
    source,
    snapshotPath: DEFAULT_SNAPSHOT_PATH,
    outPath: DEFAULT_OUT_PATH,
  });
  console.log(`[codegen-api] done.`);
}

// Run as CLI when invoked directly (not when imported by tests).
const invokedAsScript = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (invokedAsScript) {
  main(process.argv.slice(2)).catch((err: unknown) => {
    console.error('[codegen-api] failed:', err);
    process.exit(1);
  });
}
